import { PERMISSIONS } from './permissions';

export type Role = 'OWNER' | 'BARBER' | 'CLIENT';

export const ROLE_PERMISSIONS: Record<Role, string[]> = {
  OWNER: ['*'],

  BARBER: [
    PERMISSIONS.CREATE_SERVICE,
    PERMISSIONS.UPDATE_SERVICE,
    PERMISSIONS.DELETE_SERVICE,
    PERMISSIONS.VIEW_SERVICE,

    PERMISSIONS.CREATE_APPOINTMENT,
    PERMISSIONS.UPDATE_APPOINTMENT,
    PERMISSIONS.DELETE_APPOINTMENT,
    PERMISSIONS.VIEW_APPOINTMENT,

    PERMISSIONS.CREATE_CUSTOMER,
    PERMISSIONS.UPDATE_CUSTOMER,
    PERMISSIONS.DELETE_CUSTOMER,
    PERMISSIONS.VIEW_CUSTOMER,

    PERMISSIONS.CREATE_PORTFOLIO,
    PERMISSIONS.DELETE_PORTFOLIO,
    PERMISSIONS.VIEW_PORTFOLIO,
  ],

  CLIENT: [
    PERMISSIONS.CREATE_APPOINTMENT,
    PERMISSIONS.VIEW_OWN_APPOINTMENT,
    PERMISSIONS.UPDATE_OWN_PROFILE,
    PERMISSIONS.VIEW_SERVICE,
    PERMISSIONS.VIEW_PORTFOLIO,
  ],
};
